### ISSUE TITLE
algorithm?

### ISSUE THREAD

**Issue by donnut** [js-org/stats.js.org#1]
Can you explain how the ranking is computed? E.g., how do you  normalize the stars and forks, what weight factors do you use? Just curious.

**Comment by indus** [comment]
The stars/forks ratio is roughly 2:1 (depends on the overall number of stars and forks). The mean value of the distribution (weibull) is used to shift and shrink these raw points (without changing the order). The rank is then used to make points appear progressiv (angular needs more stars/forks to gain a point than a newcomer).
I will go more in detail soon, but have to go to my day job now...

**Comment by indus** [comment]
I think it may be most efficent to show you the critical code:

``` javascript
console.log('STATS | data_dump')
console.time("data_dump");

var sqlite3 = require('sqlite3').verbose()
var fs = require('fs')

var db = new sqlite3.Database(__dirname + '/stats.sqlite');

var reg_escape = /[^\w\s,;.:!?#()\[\]]/gi;

var query_meta = "SELECT f,SUM(p)/1000000 AS p,SUM(d)/1000000 AS d,SUM(w)/1000000 AS w,SUM(m)/1000000 AS m FROM(SELECT f,(pw+pf*f) AS p,(dw+df*f) AS d,(ww+wf*f) AS w,(mw+mf*f)AS m FROM (SELECT(SELECT(SUM(watchers)*1.0 /SUM(forks))/2 FROM recs)AS f,* FROM(SELECT * FROM(SELECT id,MAX(watchers)AS pw,MAX(forks)AS pf,MIN(watchers)AS dw,MIN(forks)AS df FROM recs WHERE dt >= datetime('now','-33 hours') GROUP by id)LEFT JOIN (SELECT id,MIN(watchers) AS ww,MIN(forks)AS wf FROM recs WHERE dt >= datetime('now','-7 days')GROUP by id)USING(id)LEFT JOIN(SELECT id,MIN(watchers)AS mw,MIN(forks) AS mf FROM recs WHERE dt >= datetime('now','-1 month')GROUP by id )USING(id)))ORDER BY p DESC LIMIT 10000)";
var query_recs = "SELECT * FROM(SELECT id AS id,p AS p,(d/? + d/?)/2 AS d,(w/? + w/?)/2 AS w,(m/? + m/?)/2 AS m,name AS n, COALESCE(homep,url) AS u, desc AS i FROM(SELECT id, (MAX(watchers) + MAX(forks) * ?) / ? AS p, MIN(watchers) + MIN(forks) * ? AS d FROM recs WHERE dt >= datetime('now', '-33 hours') GROUP by id ORDER BY p DESC LIMIT 10000) LEFT JOIN (SELECT id, MIN(watchers)+MIN(forks)*? AS w FROM recs WHERE dt >= datetime('now','-7 days') GROUP by id ) USING (id) LEFT JOIN (SELECT id, MIN(watchers)+MIN(forks)*? AS m FROM recs WHERE dt >= datetime('now','-1 month') GROUP by id ) USING (id) LEFT JOIN meta USING (id)) ORDER BY p DESC"

db.serialize(function () {
    db.get(query_meta, function (err, m) {
        db.all(query_recs, [m.p, m.d, m.p, m.w, m.p, m.m, m.f, m.p, m.f, m.f, m.f], function (err, recs) {

            var l = recs.length;

            for (var i = 0, r; i < l && (r = recs[i]); i++)r.r = i;

            recs.sort(function (a, b) { return b.d - a.d })
            for (var i = 0, r; i < l && (r = recs[i]); i++) { r.d = r.p - r.d; r.dd = i-r.r; }
            recs.sort(function (a, b) { return b.d - a.d })
            for (var i = 0, r; i < l && (r = recs[i]); i++) { r.rd = i; r.d = Math.round(r.d) }            ;

            recs.sort(function (a, b) { return b.w - a.w })
            for (var i = 0, r; i < l && (r = recs[i]); i++) { r.w = r.p - r.w; r.dw = i-r.r; }
            recs.sort(function (a, b) { return b.w - a.w })
            for (var i = 0, r; i < l && (r = recs[i]); i++) { r.rw = i; r.w = Math.round(r.w) }

            recs.sort(function (a, b) { return b.m - a.m })
            for (var i = 0, r; i < l && (r = recs[i]); i++) { r.m = r.p - r.m; r.dm = i-r.r; }
            recs.sort(function (a, b) { return b.m - a.m })
            for (var i = 0, r; i < l && (r = recs[i]); i++) { r.rm = i; r.m = Math.round(r.m) }

            recs.sort(function (a, b) { return a.r - b.r })

            var csv_arr = ['id,r,p,d,w,m,rd,rw,rm,dd,dw,dm,n,u,i'];

            for (var i = 0, r; i < l && (r = recs[i]); i++) {
                csv_arr.push(
                    r.id + ',' +
                    ("000"+r.r).slice(-4) + ',' +
                    Math.round(r.p) + ',' +
                    r.d + ',' +
                    r.w + ',' +
                    r.m + ',' +
                    ("000"+r.rd).slice(-4) + ',' +
                    ("000"+r.rw).slice(-4) + ',' +
                    ("000"+r.rm).slice(-4) + ',' +
                    r.dd + ',' +
                    r.dw + ',' +
                    r.dm + ',' +
                    (r.n ?'"' + r.n + '"':'') + ',' +
                    (r.u ?'"' + r.u + '"':'') + ',' +
                    (r.i ?'"' + r.i.replace(/''/g, "'").replace(reg_escape, '').replace(/[^\x20-\x7E]+/g, '') + '"':'')
                )
            }

            fs.writeFile(__dirname + "/../stats.js.org/_data/recs.csv", csv_arr.join('\n'), 'ascii', function (err) {
                if (err) console.log("fs-error:", err);
                console.timeEnd("data_dump");
            })
        });
    });
});
```

**Comment by indus** [comment]
to give you some background: Everything runs locally at my home on a BananaPI as a headless system directly connected to my router (thats kind of a proof of concept that JS could be used for a "service" without paying anybody for a server; thanks to GitHubs free hosting, JS.ORGs free domain and these cheap SoC dev boards).

a "npm run ..." command triggered by a chronjob (or on a reboot) is running three subtasks "data_fetch" (collecting the data from the GitHub API stuffing it into a sqlite DB), "data_dump" (getting the data out of the DB writing a CSV file to the local copy of this repo), "push" (just a automatic push to the GitHub repo). In the end jekyll is building the pages directly from the CSV on GitHub (but thats out of scope)

What I have posted is the "data_dump" step. So imagin a sqlite data-base with a table `recs` and the columns `id` (GitHub-ID of a repo), `dt` (DateTime of a recored), `watchers` (watchers/stars at this timestamp), `forks` (forks at this timestamp), and a second table `meta` with name, url and description

the "heavy lifting" is done by two sqlite requests. The first one called `meta` gives me statsistical parameters for the complete set of records, the second one (`recs`) applies them to and returns the first 10k rows in the set. After the query finished I just calculate some indicies and deltas in JavaScript and write the file.

**Comment by indus** [comment]
The sqlite queries are nested and joined alot. And its not that easy to see what is going on, so:

**"meta"-query values**

`f_meta`  ("overall stars/forks ratio"): `(sum(stars)/sum(forks))/2` (that later gives forks twice as much weight to refect the higher involvment)
`f_meta` is used to calculate the sum of "raw points" for all repos together for different timestamps (actually I use min, max in a timeframe for performance reasons, and for the case I missed a certain timestamp to record); and I divide by 1000k just to scale the values (in an equal distribution every repo would have 100 raw points and all 10k together 1000k).

values beside `f_meta` returnd by the query:
`p_meta` ("sum of points now")
`d_meta` ("sum of points yesterday")
`w_meta` ("sum of points last week")
`m_meta` ("sum of points last month")

**Comment by indus** [comment]
**"recs"-query values**

besides joining with all the meta-data (name, url) of the repos, thats the step where the points for all the repos are getting calculated (points `p` are just like the "raw points" already explained with "overall stars/forks ratio" and "100 points for everybody" taken into account)

_But now comes the place where I could get trouble when a mathematician is looking at it. Because I´m doing something that has no scientific background._

Points for a yesterday, last week, and last month are calculated by (example yesterday; `d` is the same as `p` only for yesterday):

points_yesterday = `(d/p_meta + d/d_meta)/2`

its the same for last week, and last month

then it is just calculating deltas (e.g. "current points" - "yesterdays points", etc...), sorting and indexing of all the records (done in JavaScript)

Don´t ask me why I´m doing it exactly that way - but what this calculation returns gives newcomers and mature projects a good (equal?) chance to rank high in the trending section.(DAY,WEEK,MONTH column in the table); and matches to some degree [GitHub trending](https://github.com/trending?l=javascript) but seems to be a bit more robust.

You may be surprised why "yesterday" is 33 hours in the past of "now": Thats because I don´t want to get a record from within the period of 24 hours - but the last record before. Also the "data_fetch" process takes some time (~10 minutes), and just because it startes every 8 hours doesn´t mean it has finished at that time; So  24 hours + 8 hours +1 hour makes sure that I get the "yesterday" record. For MONTH, and WEEK I think it is not that important (I just take the first record in the period and not the last one in the period before)

**Comment by indus** [comment]
Sorry, for my bad english (the reason why I don´t post this stuff in a blog). If you have some questions, or suggestions to improve the process...

**Comment by donnut** [comment]
Thanks @indus for the explaination. If I understand correctly the ranking of a repo is based by comparing the quotient of its individual (stars/2*forks)-quotient with the total. The 'challange' is indeed to define what a successful repo is and this seems a good first estimate. The delta's are probable even more interesting because big, inactive projects are likely to keep their stars and forks for a long time.

**Comment by jakerella** [comment]
I completely agree with @donnut on the inactive projects... That's what has kept things like EJS (server-side templating engine for Node) popular, even though it isn't actively developed.

I think adding in a third criteria beyond stars and forks would be helpful, and I would propose something like "velocity". In other words, number of commits to master over a given period of time (previous 12 months?).

**Comment by indus** [comment]
I will have to think about it and propably implement something like that.
But I also think, you are to focused on the first column (the eternal - and sometimes historic - rank). My focus is more on the three rightmost "timeframe" columns. When you click on DAY you get almost every day a new fresh trending project in the first position. When you click on MONTH and read the first 10 you know alot of what was going on in this month, and when I add a column YEAR at some  point you will get pretty much the same result as @jakerella suggests (at least i would think so).
You propably know [GutHub Trending](https://github.com/trending?l=javascript&since=monthly) and after I have been in the list two or three times (but only for a single day ;-) I wanted to be able to track the stats of my projects not only when they are trending but also when they are just doing normal. And on the other hand I´was bored to read angular +1400 stars, react +1600 stars every single time I looked at it. I wanted to see the newcomers in that month. And the table does that pretty well even if the first column needs some improvments.

Because of the misleading RANK I already thought about setting WEEK or MONTH sorting as default.

But as I said I will have a look at the use of some one or more other parameters; and I allready have an idea...

**Comment by indus** [comment]
@jakerella I had a smoke and thought about your proposal and found two drawbacks
- this opens a door for manpulation; it would be easy to set up a bot to commit 10 times a day random stuff (even I think nobody would be that silly)
- if a new project is pushed to GitHub mainly on day X and not promoted for lets say 1 month to sort some details out (maybe fixed with a single commit) and promoted with a post on hackernews or echojs after that time and people fall in love with it and star it like crazy. Then I think it is "popular" after the post and not when all the commits where made in the beginning.

Maybe "activity" (or better "inactivity") could be used to eliminate unwanted edge cases, but popularity is only shown by the involvment of other devs (staring and forking). Of course commits may also be the work of external devs, but mostly the work of the owner or a core-team, and then it doesn´t show popularity (in my understanding of the word).

But I really thank you for these suggestions that make me think about this kind of stuff, and clearly shows me that there is some work to be done :+1:

**Comment by Flet** [comment]
Commits are an interesting metric to measure the activity of a repository. However, there are some well-used projects that are tiny modules or are considered "done". These usually have very few ongoing commits.

Tapping into some additional data like total npm downloads and/or bower statistics on downloads could help fill the gaps around usage.

As it is, the stats.js.org site is really intriguing and fun to use :) Good job!

**Comment by indus** [comment]
Thanks!
