### ISSUE TITLE
Add project description to search parameters

### ISSUE THREAD

**Issue by dortzur** [js-org/stats.js.org#3]
Currently When I search for "Carousel" I only get projects which have "carousel" in their title.
Thus I completely miss out on "Slick" which is the number one ranked carousel in the list.
Just an example of course.
If it slows down search significantly perhaps add a checkbox to enable this feature.

Awesome stuff by the way.

**Comment by indus** [comment]
Last weekend, and this week was busy. But today I found the time to implement this really benifitial feature (Thanks for requesting it :+1:). I wanted to keep the "name only" search as default because the project-description is only showing as a native tooltip and therefore is invisible on mobile browsers. So "description search" is only an opt-in to give reasonable results in all cases.

So you will find a toggle on the right of the search input to enable the "description search" (actually it searches in name AND description). If you are on a smartphone with a small screen the toggle will be hidden, but you also can prefix you request with a "+" (with or without a blank `+carousel` or `+ carousel`) to get the same results as if you would have enabled "description search". Until I find a good place for a checkbox in the layout, this is kind of a hidden feature :wink:

Hope I din´t broke something, and didn´t missed any edge cases. Leave me a note if you find a bug...

**Comment by dortzur** [comment]
Thanks!
has this gone live?
Currently i'm not seeing the toggle, and searching with a "+" gives me the following error in console:
"Uncaught SyntaxError: Invalid regular expression: /+ carousel/: Nothing to repeat"

**Comment by indus** [comment]
The bot that commits the data reverted my manual changes accidently. But I recommitted and it shouldn't happen again.

**Comment by dortzur** [comment]
Works great now, awesome! 
This is going to be very useful for me now thanks.
